/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SxKjMUCnHom
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Card, CardContent, CardFooter } from "@/components/ui/card";

export function Kanban() {
  return (
    <div className="flex flex-col h-screen bg-background">
      <header className="flex items-center justify-between px-6 py-4 border-b">
        <h1 className="text-2xl font-semibold flex gap-7">My readme Kanban</h1>
        <div className="flex items-center gap-4">
          <div className="flex justify-center items-center py-4 pr-8 text-sm text-muted-foreground">
            Made with ❤️ by v0
          </div>
        </div>
      </header>
      <main className="flex-1 grid grid-cols-3 gap-6 p-6">
        <div className="bg-card rounded-lg shadow-md">
          <div className="px-4 py-3 border-b">
            <h2 className="text-lg font-semibold">To Do</h2>
          </div>
          <div className="p-4 space-y-4">
            <Card>
              <CardContent>
                <h3 className="text-base font-semibold">
                  Contribute to open source project
                </h3>
                <p className="text-sm text-muted-foreground">
                  Participate actively in open source software projects like
                  NodeJS or Supabse.
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@username" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-muted-foreground">
                    Alejo Rojas
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <CalendarDaysIcon className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">Jan 25</span>
                </div>
              </CardFooter>
            </Card>
            <Card>
              <CardContent>
                <h3 className="text-base font-semibold">Do laundry</h3>
                <p className="text-sm text-muted-foreground">
                  Tidy up and do laundry by Friday.
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@username" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-muted-foreground">
                    Alejo Rojas
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <CalendarDaysIcon className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">Aug 03</span>
                </div>
              </CardFooter>
            </Card>
          </div>
        </div>
        <div className="bg-card rounded-lg shadow-md">
          <div className="px-4 py-3 border-b">
            <h2 className="text-lg font-semibold">In Progress</h2>
          </div>
          <div className="p-4 space-y-4">
            <Card>
              <CardContent>
                <h3 className="text-base font-semibold">
                  Work at a YC company
                </h3>
                <p className="text-sm text-muted-foreground">
                  Ship, ship, and ship to make the world a BETTER PLACE.
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@username" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-muted-foreground">
                    Alejo Rojas
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <CalendarDaysIcon className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">Sept 24</span>
                </div>
              </CardFooter>
            </Card>
          </div>
          <div className="p-4 space-y-4">
            <Card>
              <CardContent>
                <h3 className="text-base font-semibold">
                  System Engineer Degree
                </h3>
                <p className="text-sm text-muted-foreground">
                  Halfway through the degree, keep pushing!
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@username" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-muted-foreground">
                    Alejo Rojas
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <CalendarDaysIcon className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">Dec 27</span>
                </div>
              </CardFooter>
            </Card>
          </div>
        </div>
        <div className="bg-card rounded-lg shadow-md">
          <div className="px-4 py-3 border-b">
            <h2 className="text-lg font-semibold">Done</h2>
          </div>
          <div className="p-4 space-y-4">
            <Card>
              <CardContent>
                <h3 className="text-base font-semibold">New readme view</h3>
                <p className="text-sm text-muted-foreground">
                  Implement an original and hilarious view.
                </p>
              </CardContent>
              <CardFooter className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar className="w-6 h-6 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@username" />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <span className="text-sm text-muted-foreground">
                    Alejo Rojas
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <CalendarDaysIcon className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">Jun 10</span>
                </div>
              </CardFooter>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}

function CalendarDaysIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  );
}

function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
